import Head from "next/head";
import styles from "../styles/Home.module.css";
import { PostComponent } from "../components/componentProvider";
import Post from "../types/post/post";
import { getPostList } from "../lib/parseMarkdown";
import Logo from "../components/logo/Logo";

type Props = {
  postList: Post[];
};

const Index = ({ postList }: Props) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next Typescript Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
      </Head>

      <div className={styles["section-title"]}>
        <h2 className={styles.title}>ALL</h2>
        <p className={styles.memo}>記事一覧</p>
      </div>

      <main className={styles.main}>
        {postList.map((post, index) => (
          <PostComponent post={post} key={index} />
        ))}
      </main>
    </div>
  );
};

export const getStaticProps = async () => {
  const postList = getPostList("", ["title", "date", "slug", "leading"]);

  return {
    props: { postList },
  };
};

export default Index;
